version: '3.5'
services:
    db:
        image: mysql:5.6
        container_name: atendimento-agendamento-db
        volumes:
            - ./init:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: "root"
        ports:
            - "3305:3306"
        logging:
            driver: "json-file"
            options:
                max-size: "5MB"
                max-file: "1"
    local-stack:
        image: localstack/localstack:latest
        container_name: aws-atendimento-agendamento
        ports:
            - '4563-4599:4563-4599'
            - '8055:8080'
        environment:
            - SERVICES=s3,sns,sqs
            - DEBUG=1
            - DATA_DIR=/tmp/localstack/data
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'

    wiremock:
        image: sanson/wiremock:latest
        container_name: wiremock-standalone
        ports:
            - "8090:8080"
        volumes:
            - ./mock/files:/opt/wiremock/__files
            - ./mock/mappings:/opt/wiremock/mappings